# The URL the site will be built for
base_url = "https://tamer.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
    {name = "tags", paginate_by = 5, feed = true},
    {name = "categories", paginate_by = 5, feed = true},
]


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The site theme to use.
theme = "blow"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-dark.css" },
  { theme = "ayu-light", filename = "syntax-light.css" },
]

[extra]
# Put all your custom variables here
enable_search = true
enable_sidebar = true
enable_adsense = false
enable_multilingue = false
# adsense_link = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"

# [extra.lang]
# items = [
#     { lang = "en", links = [
#         { base_url = "/", name = "English" },
#         { base_url = "/fr", name = "French" },
#     ] },
#     { lang = "fr", links = [
#         { base_url = "/", name = "Anglais" },
#         { base_url = "/fr", name = "Français" },
#     ] },
# ]

[extra.navbar]
items = [
    { lang = "en", links = [
        { url = "/blog", name = "Tech Blog" },
        { url = "/categories", name = "Categories" },
        { url = "/tags", name = "Tags" },
        { url = "/about", name = "About" },
    ] },
    { lang = "fr", links = [
        { url = "/fr", name = "Accueil" },
        { url = "/fr/categories", name = "Categories" },
        { url = "/fr/tags", name = "Tags" },
    ] },
]
title = "Home"

[extra.sidebar]
items = [
    { lang = "en", links = [
        { url = "/blog", name = "Blog" },
        { url = "/markdown", name = "Markdown" },
    ] },
    { lang = "fr", links = [
        { url = "/fr/blog", name = "Blog" },
        { url = "/fr/markdown", name = "Markdown" },
    ] },
]

# Index page
[extra.index]
title = "Tamer Alamiri"
image = "https://github.com/tameralamiri/tameralamiri.github.io/blob/main/static/imgs/index.jpeg?raw=true"
image_alt = "Placeholder text describing the index's image."

[extra.default_author]
name = "Tamer Alamiri"
avatar = "https://github.com/tameralamiri/tameralamiri.github.io/blob/main/static/imgs/index.jpeg?raw=true"
avatar_alt = "Placeholder text describing the default author's avatar."

[extra.social]
codeberg = ""
github = "https://github.com/tameralamiri"
gitlab = ""
twitter = ""
mastodon = ""
linkedin = "https://www.linkedin.com/in/tamer-alamiri/"
stackoverflow = "" 
telegram = ""
email = "tameralamiri@gmail.com"

[extra.favicon]
favicon = "/icons/favicon.ico"
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
android_chrome_512 = "/icons/android-chrome-512x512.png"
android_chrome_192 = "/icons/android-chrome-192x192.png"
manifest = "/icons/site.webmanifest"